no-permission: "§cYou do not have permission to use this command."

enchant-success: "§aSuccessfully enchanted {player}'s item."

list-format:
  - "§6§lZyber Custom Enchants"
  - "§7Available Enchants:"
